# Generated by Django 5.0.2 on 2024-05-04 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('log_status', models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], max_length=20, verbose_name='статус попытки')),
                ('response', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('log_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailing.client', verbose_name='подписчик')),
                ('log_emailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailing.emailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
