# Generated by Django 5.0.2 on 2024-05-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0002_emailinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailing',
            name='emailing_clients',
            field=models.ManyToManyField(blank=True, null=True, to='emailing.client', verbose_name='подписчики'),
        ),
    ]
