# Generated by Django 5.0.2 on 2024-05-05 07:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0003_alter_emailing_emailing_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surname',
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='emailing',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailing',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='название рассылки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='emailing',
            name='emailing_clients',
            field=models.ManyToManyField(to='emailing.client', verbose_name='клиенты'),
        ),
        migrations.AlterField(
            model_name='emailing',
            name='emailing_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='emailing',
            name='emailing_status',
            field=models.CharField(choices=[('started', 'Запущена'), ('created', 'Создана'), ('done', 'Завершена')], default='created', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='emailing',
            name='send_periodicity',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='emailing',
            name='time_to_send',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='время рассылки'),
        ),
    ]
