# Generated by Django 5.0.2 on 2024-05-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0004_remove_client_comment_remove_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailing',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
    ]
