# Generated by Django 5.0.2 on 2024-05-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0005_alter_emailing_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailing',
            name='emailing_clients',
            field=models.ManyToManyField(to='emailing.client'),
        ),
    ]
