# Generated by Django 5.0.2 on 2024-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0006_alter_emailing_emailing_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailing',
            name='emailing_clients',
            field=models.ManyToManyField(to='emailing.client', verbose_name='клиенты'),
        ),
        migrations.AlterField(
            model_name='emailing',
            name='time_to_send',
            field=models.TimeField(verbose_name='время рассылки'),
        ),
    ]
