# Generated by Django 5.0.2 on 2024-05-05 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0009_rename_message_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailing.messages'),
        ),
    ]
