# Generated by Django 5.0.2 on 2024-05-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0010_emailing_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailinglog',
            name='log_client',
        ),
    ]
