# Generated by Django 5.0.2 on 2024-05-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0011_remove_emailinglog_log_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailinglog',
            name='log_status',
            field=models.CharField(choices=[('CREATED', 'Создано'), ('FINISHED', 'Завершено')], max_length=20, verbose_name='статус попытки'),
        ),
    ]
