# Generated by Django 5.0.2 on 2024-05-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0013_alter_emailing_emailing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailing',
            name='send_periodicity',
            field=models.CharField(choices=[('ежедневно', 'daily'), ('еженедельно', 'weekly'), ('ежемесячно', 'monthly')], verbose_name='периодичность'),
        ),
    ]
