# Generated by Django 5.0.2 on 2024-05-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0014_alter_emailing_send_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailing',
            name='emailing_status',
            field=models.CharField(choices=[('завершена', 'завершена'), ('создана', 'создана'), ('запущена', 'запущена')], default='создана', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='emailinglog',
            name='log_status',
            field=models.CharField(choices=[('УСПЕШНО', 'УСПЕШНО'), ('НЕ УСПЕШНО', 'НЕ УСПЕШНО')], max_length=20, verbose_name='статус попытки'),
        ),
    ]
