# Generated by Django 5.0.2 on 2024-05-05 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0015_alter_emailing_emailing_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Text_Messages',
        ),
        migrations.RemoveField(
            model_name='emailing',
            name='message',
        ),
    ]
