# Generated by Django 5.0.2 on 2024-05-12 00:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0017_emailing_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text_Messages',
            new_name='Messages',
        ),
    ]
