# Generated by Django 5.0.2 on 2024-08-23 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0018_rename_text_messages_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailing',
            options={'permissions': [('switch_status', 'изменение статуса'), ('view_mailing', 'отображать рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='emailinglog',
            options={'verbose_name': 'попытка рассылки', 'verbose_name_plural': 'попытки рассылки'},
        ),
        migrations.RemoveField(
            model_name='emailing',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='emailing',
            name='time_to_send',
        ),
        migrations.RemoveField(
            model_name='emailinglog',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='emailinglog',
            name='log_emailing',
        ),
        migrations.AddField(
            model_name='emailing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
        migrations.AddField(
            model_name='emailing',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AddField(
            model_name='emailinglog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailing.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='emailinglog',
            name='last_try',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последней попытки'),
        ),
        migrations.AddField(
            model_name='emailinglog',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailing.emailing', verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='emailing',
            name='emailing_clients',
            field=models.ManyToManyField(related_name='mailing_settings', to='emailing.client', verbose_name='клиенты'),
        ),
        migrations.AlterField(
            model_name='emailing',
            name='emailing_status',
            field=models.CharField(choices=[('завершена', 'завершена'), ('создана', 'создана'), ('запущена', 'запущена')], default='created', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='emailing',
            name='send_periodicity',
            field=models.CharField(choices=[('ежедневно', 'daily'), ('еженедельно', 'weekly'), ('ежемесячно', 'monthly')], default='Ежедневно', verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='emailinglog',
            name='log_status',
            field=models.CharField(choices=[('STATUS_OK', 'УСПЕШНО'), ('STATUS_FAILED', 'НЕ УСПЕШНО')], default='ok', max_length=20, verbose_name='статус попытки'),
        ),
        migrations.AlterField(
            model_name='emailinglog',
            name='response',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='ответ сервера'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.TextField(verbose_name='тело письма'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
