# Generated by Django 5.0.2 on 2024-08-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0020_alter_emailing_emailing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailing',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
    ]
