# Generated by Django 5.0.2 on 2024-08-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0022_alter_emailing_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
    ]
