# Generated by Django 5.0.2 on 2024-08-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0023_alter_emailing_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='статус активности'),
        ),
    ]
